config/routes.rb
Rails.application.routes.draw do

  resources :withdrawals do
    collection do
      get '/all' => 'withdrawals#all', :as => :all
      get '/archive' => 'withdrawals#archive', :as => :archive
    end
  end
  resources :types
  resources :operations do
    collection do
      get '/:year/:month' => 'operations#calendar_month', :as => :calendar_month, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ }
      get '/year/:year' => 'operations#calendar_year', :as => :calendar_year, :constraints => { :year => /\d{4}/ }
      get 'max'
    end
  end
  resources :users , except: :destroy

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  root :to => 'angular#index'
  get '/pages/:path.html' => 'angular#page', :constraints => { :path => /.+/  }

end

app/models/operation.rb
# == Schema Information
#
# Table name: operations
#
#  id         :integer          not null, primary key
#  note       :string
#  sign       :string           not null
#  amount     :decimal(12, 2)   not null
#  type_id    :integer          not null
#  user_id    :integer          not null
#  date       :date             not null
#  year       :integer          not null
#  month      :integer          not null
#  day        :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Operation < ApplicationRecord
  include Repeatable
  set_start_date :date
  belongs_to :type, touch: true
  belongs_to :user, touch: true

  validates :note, length: { maximum: 4000 }, presence: false
  validates :sign, presence: true
  validates :amount, presence: true
  validates :type_id, presence: true
  validates :user_id, presence: true
  validates :date, presence: true

  scope :by_month_and_sign, lambda { |year, month, sign| by_month(year, month).joins(:type, :user).where(sign: sign).order("types.name ASC, users.name ASC, operations.day ASC") }

  scope :by_month, lambda { |year, month| where(year: year, month: month) }

  scope :tot_operations_per_type_per_year, lambda { | year| select("*, sum(amount) sum_amount, master_types_types.name types_name").joins(:type).merge(Type.joins(:master_type)).order("master_types_types.name ASC").group("master_types_types.id").where(year: year) }

  def self.maximum_update(year)
    if year.blank?
      Operation.maximum(:updated_at)
    else
      Operation.where(year: year).maximum(:updated_at)
    end
  end

  before_save do
     self.year = date.year
     self.month = date.month
     self.day = date.day
   end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /operations.json
  def index
    @operations = Operation.joins(:type, :user).order('date DESC')
    if params[:year]
      @operations.where!(year: params[:year])
    end
    if params[:month]
      @operations.where!(month: params[:month])
    end
    if params[:type_id]
      @operations.where!(type_id: params[:type_id])
    end
    if params[:q]
      @operations.where!("operations.note like :key or operations.amount like :key or users.name like :key or types.name like :key", key: "%"+params[:q]+"%")
    end
  end

  def max
    respond_to do |format|
      format.json { render :json => Operation.select("id, year, FROM_UNIXTIME(max(updated_at)) max").group(:year).to_json }
    end
  end

  def calendar_month
    respond_to do |format|
      format.json do
        @operations = Operation.by_month(params[:year], params[:month]).includes(:type, :user).order(:day)
        render :index
      end
    end
  end

  def calendar_year
    respond_to do |format|
      format.json do
        @operations = Operation.where(year: params[:year]).includes(:type, :user).order(:month)
        render :index
      end
    end
  end

  # GET /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)
    respond_to do |format|
      if @operation.save
        operation = @operation.as_json(include: { type: { only: [:id, :name, :spending_roof, :spending_limit] }, user: { only: [:id, :name]} })
        ActionCable.server.broadcast 'operations', message: operation, method: "create", max: @operation.updated_at.to_i, year: @operation.year
        format.json { render :show, status: :created, location: @operation }
      else
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        operation = @operation.as_json(include: { type: { only: [:id, :name, :spending_roof, :spending_limit] }, user: { only: [:id, :name]} })
        ActionCable.server.broadcast 'operations', message: operation, method: "update", max: @operation.updated_at.to_i, year: @operation.year
        format.json { render :show, status: :ok, location: @operation }
      else
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    operation = @operation.as_json(include: { type: { only: :name }, user: { only: :name} })
    last_operation = Operation.where(year: @operation.year).last
    last_operation.update(updated_at: Time.now)
    ActionCable.server.broadcast 'operations', message: operation, method: "destroy", max: last_operation.updated_at.to_i, year: @operation.year
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.require(:operation).permit(:note, :date, :sign, :amount, :type_id, :user_id, :repeat, :interval_repeat, :type_repeat, :week_repeat, :wday_repeat, :last_date_repeat)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper

  def id_and_maximum_updated_at model
    obj = model.id_and_maximum_updated_at
    "#{obj.id}-#{obj.max_updated_at}"
  end

  def diff_cumulus operations_cumulus, operations_cumulus_prev
    (operations_cumulus.where(sign: "+").sum(:amount) - operations_cumulus.where(sign: "-").sum(:amount)) - (operations_cumulus_prev.where(sign: "+").sum(:amount) - operations_cumulus_prev.where(sign: "-").sum(:amount))
  end

  def subtraction pos_operations, neg_operations
    pos_operations.sum(:amount) - neg_operations.sum(:amount)
  end

  def balance operation_per_month
    number_to_currency(subtraction(operation_per_month.where(sign: "+"), operation_per_month.where(sign: "-")))
  end

  def tot_balance operations_per_month
    number_to_currency(operations_per_month.sum {|o| o.where(sign: "+").sum(:amount)} - operations_per_month.sum {|o| o.where(sign: "-").sum(:amount)})
  end

  def cumulative_balance operations_cumulus, i
    number_to_currency(subtraction(operations_cumulus.where(month: (1..i), sign: "+"), operations_cumulus.where(month: (1..i), sign: "-")))
  end

  def quarterly_balance operations_cumulus, i
    number_to_currency(subtraction(operations_cumulus.where(month: ((i*3)+1..(i+1)*3), sign: "+"), operations_cumulus.where(month: ((i*3)+1..(i+1)*3), sign: "-")))
  end

  def quarterly_balance_diff operations_cumulus_prev, operations_cumulus, i
    month = ((i*3)+1..(i+1)*3)
    prev_year = operations_cumulus_prev.where(month: month)
    t_year = operations_cumulus.where(month: month)
    abs_diff = (100.to_f/(prev_year.where(sign: "+").sum(:amount) - prev_year.where(sign: "-").sum(:amount))*(t_year.where(sign: "+").sum(:amount) - t_year.where(sign: "-").sum(:amount)))-100
    number_to_percentage(abs_diff, precision: 1, strip_insignificant_zeros: true)
  end

  def difference_in_balance operations_cumulus, i
    subtraction(operations_cumulus.where(month: ((i*3)+1..(i+1)*3), sign: "+"), operations_cumulus.where(month: ((i*3)+1..(i+1)*3), sign: "-"))
  end

  def previous_month_diff operations, sign, month
    number_to_percentage((100.to_f/operations.where(sign: sign, month: month-1).sum(:amount).to_f*operations.where(sign: sign, month: month).sum(:amount).to_f)-100, precision: 1, strip_insignificant_zeros: true)
  end

  def saved_or_params obj, field
    obj.method(field).call || params[field]
  end

  def saved_or_default field, default
    field || default
  end

  def currency_unit
    t(:unit, scope: [:number, :currency, :format])
  end

end

app/views/operations/_operation_table.html.erb
<tr>
  <td><%= operation.day %></td>
  <td><%= operation.type.name %></td>
  <td><%= operation.user.name %></td>
  <td class="<%= operation.sign == '-' ? 'negative' : '' %>">
    <%= operation.amount %>
  </td>
  <td><%= operation.note.blank? ? "" : "K" %></td>
  <td><%= link_to 'Show', operation %></td>
  <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
  <td><%= link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/operations/_tot_month_operation.html.erb
<% cache [operations_per_type.where(user_id: user.id).maximum(:updated_at),"monthly_charts1"] do %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">
        <%= user.name %>
      </h3>
    </div>
    <div class="panel-body">
      <div class="row-fluid">
        <% { "Uscite": "-", "Entrate": "+"}.each do |k,v| %>
          <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title"><%= k %></h3>
              </div>
              <div class="panel-body">
                <%= pie_chart operations_per_type.where(sign: v, user_id: user.id).map { |o| [o.types_name, o.sum_amount] }, id: "chart-#{user.id}-#{k}" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/operations/calendar.html.erb
<h1>Operations</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Type</th>
      <th>User</th>
      <th>Sign</th>
      <th>Amount</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @negative_operations.each do |operation| %>
      <%= render partial: 'operation_table', locals: { operation: operation } %>
    <% end %>
    <tr>
      <th colspan="4">Totale Uscite</th>
      <th><%= @negative_operations.sum('amount') %></th>
      <th colspan="3"></th>
    </tr>
    <% @positive_operations.each do |operation| %>
      <%= render partial: 'operation_table', locals: { operation: operation } %>
    <% end %>
    <tr>
      <th colspan="4">Totale Entrate</th>
      <th><%= @positive_operations.sum('amount') %></th>
      <th colspan="3"></th>
    </tr>

    <tr>
      <th colspan="4">Saldo</th>
      <th>
        <%= @positive_operations.sum('amount') - @negative_operations.sum('amount') %>
      </th>
      <th colspan="3"></th>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Operation', new_operation_path %>